//ny ide: dagforslag:

const suggestions = {
  mat: [
    "Pizza med masse ost",
    "Sushi med laks",
    "En skikkelig taco-kveld",
    "Hjemmelaget suppe",
    "Burger med fries",
    "Pannekaker til middag",
    "Pasta carbonara",
    "Grillet kylling med salat",
    "Vegansk curry",
    "Ramen",
  ],
  hobbyer: [
    "Lese en bok",
    "Spille dataspill",
    "Tegne eller male",
    "Strikke eller hekle",
    "Lære et nytt programmeringstriks",
    "Se en film eller serie",
    "Prøve et nytt brettspill",
    "Ta bilder ute",
    "Skrive dagbok eller en liten tekst",
    "Bake noe godt",
  ],
  trening: [
    "Gå en tur i nabolaget",
    "Jogge en kort runde",
    "Ta en yoga-økt",
    "Styrketrening med egen kroppsvekt",
    "Gå på fjelltur",
    "Sykle en liten tur",
    "Prøve en dansetrening",
    "Hoppe tau",
    "Trene med YouTube-video",
    "Spille fotball eller en ballidrett",
  ],
};